export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SELECT_MIN_RATING = 'SELECT_MIN_RATING';
export const FETCH_TMDB_CONFIG = 'FETCH_TMDB_CONFIG';
export const FETCH_GENRES = 'FETCH_GENRES';
export const SELECT_GENRES = 'SELECT_GENRES';
